---
- name: Configure Ethernet Interfaces on Palo Alto Panorama
  hosts: panorama
  connection: local
  gather_facts: no

  vars:
    template_name: "tmpl-global"
    interfaces:
      - { if_name: "ethernet1/1", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/2", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/3", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/4", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/5", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/6", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/7", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/8", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/9", mode: "layer3", enable_dhcp: false }
      - { if_name: "ethernet1/10", mode: "layer3", enable_dhcp: false }

  tasks:
    - name: Create Ethernet Interfaces in tmpl-global
      paloaltonetworks.panos.panos_interface:
        provider: "{{ provider }}"
        template: "{{ template_name }}"
        if_name: "{{ item.if_name }}"
        mode: "{{ item.mode }}"
        enable_dhcp: "{{ item.enable_dhcp }}"
      loop: "{{ interfaces }}"